version: "3"
services:
  apt_mirror-list:
    container_name: apt_mirror-list
    image: apt_mirror-list:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: /bin/sh -c "while sleep 1000; do :; done"
